name: 1. Deploy_AVNM

on: 
    workflow_dispatch:

env:
    LOCATION: "canadacentral"
    RESOURCE_GROUP: "NetOpsToolkit-RG"
    NETWORK_MANAGER: "NetworkManager-01"
    SECURITY_ADMIN_CONFIG: "CentralSecurityAdminRules"
    SUBSCRIPTION_ID: ${{ secrets.AZURE_CONNECTIVITY_SUBSCRIPTION_ID }}

permissions:
    id-token: write
    contents: read

jobs:
    Deploy_AzureVirtualNetworkManager:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Azure Login
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Set Az Context
              uses: azure/cli@v2
              with:
                  azcliversion: latest
                  inlineScript: |
                    az account set --subscription $SUBSCRIPTION_ID
                    az account show

            - name: Deploy AVNM
              uses: azure/cli@v2
              with:
                  azcliversion: latest
                  inlineScript: |
                    az stack sub create \
                    --name "AVNM-DeploymentStack" \
                    --location $LOCATION \
                    --template-file AVNM/avnm.bicep \
                    --parameters AVNM/avnm.bicepparam \
                    --action-on-unmanage 'detachAll' \
                    --deny-settings-mode 'denyDelete' \
                    --deny-settings-excluded-principals '${{ secrets.SPN_OBJECT_ID }}'

            - name: Upgrade Azure CLI and Extensions
              run: |
                az upgrade --yes
                az extension remove --name virtual-network-manager || true
                az extension add --name virtual-network-manager

            - name: Commit AVNM Security Admin Configuration
              uses: azure/cli@v2
              with:
                azcliversion: latest
                inlineScript: |
                    az network manager post-commit \
                        --resource-group $RESOURCE_GROUP \
                        --name $NETWORK_MANAGER \
                        --commit-type SecurityAdmin \
                        --configuration-ids "/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.Network/networkManagers/$NETWORK_MANAGER/securityAdminConfigurations/$SECURITY_ADMIN_CONFIG" \
                        --target-locations $LOCATION