name: 1. Deploy-NSGRules

on: 
  workflow_dispatch:
    inputs:
      NSGConfig:
        type: string
        description: 'Provide NSGConfig list for this deployment (e.g. app456,empty-nic)'
        required: true
      Subscription:
        type: choice
        description: 'Select Subscription'
        options:
          - Application01
          - Application02
        required: true

env:
  Location: "canadacentral"

permissions:
  id-token: write
  contents: read

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      nsglist: ${{ steps.set-matrix.outputs.nsglist }}
    steps:
      - id: set-matrix
        run: |
          arr=$(echo "${{ github.event.inputs.NSGConfig }}" | awk -F',' '{for(i=1;i<=NF;i++) printf "\"%s\"%s", $i, (i<NF?",":"") }')
          echo "nsglist=[$arr]" >> $GITHUB_OUTPUT

  Deploy-NSGRules:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nsgconfig: ${{ fromJson(needs.prepare-matrix.outputs.nsglist) }}
    name: Deploy-NSGRules-${{ matrix.nsgconfig }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set Subscription ID Env
        shell: bash
        run: |
          sub_var="AZURE_SUBSCRIPTION_ID_${{ github.event.inputs.Subscription }}"
          sub_var_upper=$(echo $sub_var | tr '[:lower:]' '[:upper:]')
          eval "SUB_GUID=\${$sub_var_upper}"
          echo "SUB_GUID=$SUB_GUID" >> $GITHUB_ENV
        env:
          AZURE_SUBSCRIPTION_ID_APPLICATION01: ${{ vars.Application01 }}
          AZURE_SUBSCRIPTION_ID_APPLICATION02: ${{ vars.Application02 }}

      - name: Set Az Context
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account set --subscription "$SUB_GUID"
            az account show

      - name: Deploy-NSGRules
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az deployment sub create \
              --name "NSG-Deployment-${{ matrix.nsgconfig }}-${{ github.job }}" \
              --location ${{ env.Location }} \
              --template-file SecurityRules/modules/nsg.bicep \
              --parameters SecurityRules/NSGConfig/${{ matrix.nsgconfig }}.bicepparam