name: 4. Deploy-SourceControl

on: 
    workflow_dispatch:

env:
    Location: "canadacentral"
    ResourceGroupName: "NetOpsToolkit-RG"
    AutomationAccountName: "NetOpsToolkit-AA"
    SourceControlName: "cloud-netops-toolkit"
    SourceType: "GitHub"
    Branch: "main"
    FolderPath: "/AutomationAccount/Runbooks"

permissions:
    id-token: write
    contents: read

jobs:
    Deploy-SourceControl:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Azure Login
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Deploy Source Control (Azure CLI)
              run: |
                az account set --subscription "${{ secrets.AZURE_CONNECTIVITY_SUBSCRIPTION_ID }}"

                az automation source-control create \
                  --automation-account-name "${{ env.AutomationAccountName }}" \
                  --resource-group "${{ env.ResourceGroupName }}" \
                  --name "${{ env.SourceControlName }}" \
                  --repo-url "https://github.com/${{ github.repository }}.git" \
                  --source-type "${{ env.SourceType }}" \
                  --branch "${{ env.Branch }}" \
                  --folder-path "${{ env.FolderPath }}" \
                  --access-token "${{ secrets.GH_TOKEN }}" \
                  --token-type "PersonalAccessToken" \
                  --publish-runbook true \
                  --auto-sync true

                az automation source-control sync-job create \
                  --automation-account-name "${{ env.AutomationAccountName }}" \
                  --resource-group "${{ env.ResourceGroupName }}" \
                  --source-control-name "${{ env.SourceControlName }}" \
                  --job-id "$(uuidgen)" \
                  --commit-id ""
